name: Image Downloader

on:
  push:
    branches:
      - '**'

jobs:
  download_images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget

    - name: Download images and replace links
      run: |
        # Find new image links added to markdown files
        image_links=$(git diff-tree --no-commit-id --name-only -r HEAD -- '*.md*' | xargs grep -Eo '(!\[.*\]\(([^)]+)\)|<img[^>]*src="([^"]+)")' | grep 'http' | sed -n -E 's/.*\(([^)]+)\)|.*src="([^"]+)".*/\1\2/p')

        # Download images to public directory and replace links
        for link in $image_links; do
          # Extract the image file name
          image_name=$(basename "$link")

          # Download the image to the public directory
          wget -q -O "public/$image_name" "$link"

          # Replace the image link with the relative link in markdown files
          sed -i '' -E "s|$link|/$image_name|g" $(git grep -l "$link" -- '*.md*')
        done
    - name: Commit changes
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "GitHub Actions Bot"

        git add public/ *.md
        git diff --quiet && git diff --staged --quiet || git commit -m "Download images and update links"
        git push
